#!/bin/sh
#
# Simple build script to build all 3 cpu models in one go.
#
# Usage: MAKE-ALL buildtarget
#
# where buildtarget is for example nbaxp (NetBSD for Alpha AXP, or
# any other little-endian 64-bit CPU).

DEFBUILD=nbaxp

# TOP=/some/where/klh10
# Removed "/bld" from current directory, if it's there
case "${PWD}" in
    */bld)
	TOP="${PWD%/bld}"
	;;
    */bld/*)
	DEFBUILD="${PWD##*/}"
	TOP="${PWD%/bld/*}"
	;;
    *)
	TOP="$PWD"
	;;
esac

BUILD=${1-$DEFBUILD}

cd $TOP || exit 1

echo "This script builds all PDP-10 variants for host $BUILD."

buildone() {
(
    model="$1"

    export KLH10_HOME=$TOP/new/${BUILD}-${model}
    mkdir -p ${KLH10_HOME}
    cd bld/$BUILD
    make clean
    make base-${model} CONFFLAGS_AUX=-DKLH10_I_CIRC=1
    make tapedd vdkfmt wxtest enaddr
    make install
)
}

echo "Building KL"
buildone kl

echo "Building KS"
buildone ks

echo "Building KS-ITS"
buildone ks-its

